name: Release

on:
  push:
    tags:
      -"v*"
jobs:
  create_release:
    name: "Release"
    runs on: "ubuntu-latest"
    steps:
      - uses: "softprops/action-gh-release@v1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          with:
          files: |
            ${{github.workspace}}
            
      - name: Add Unx, PHP, CasperJS and SlimerJS dependency files (Windows)
        if: (matrix.os == 'windows-latest')
        run: |
          
          cd "${{github.workspace}}\src"
          
          # Add unx dependencies
          Invoke-WebRequest -Uri 'https://storage.googleapis.com/tagui-dependencies/unx.zip' -OutFile unxzip.zip
          Expand-Archive -LiteralPath unxzip.zip
          MOVE-ITEM -Path  "${{github.workspace}}\src\unxzip.zip\*" -Destination "${{github.workspace}}\src"
          Remove-Item unxzip.zip
          ls
